import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr.dtype)
ty = np.array(["apple", "banana", "guava", "berry"])
print(ty.dtype)
yu = np.array([0, 1, 2, 3, 4, 5])
rt = yu.astype(bool)
print(rt)
print(rt.dtype)
tu = np.array([1, 2, 3, 4, 5])
ur = tu.copy()
tu[2] = 52
print(tu)
print(ur)
pr = tu.view()
tu[1] = 6
pr[0] = 24
print(pr)
print(tu)
print(ur.base)
print(pr.base)
nt = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(nt.shape)
tn = np.array([2, 4, 6, 8], ndmin= 5)
print(tn)
print(tn.shape)